"""assets recruitment payroll

Revision ID: c9cd8ccc5286
Revises: 2ce3a0395a7d
Create Date: 2026-07-29 10:02:08.476731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c9cd8ccc5286'
down_revision: Union[str, Sequence[str], None] = '2ce3a0395a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('laptop', 'monitor', 'keyboard', 'mouse', 'mobile', 'accessory', 'other', name='asset_category_enum'), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('available', 'assigned', 'retired', 'maintenance', name='asset_status_enum'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('applied_designation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('applied', 'interview_scheduled', 'interviewed', 'offered', 'joined', 'rejected', name='candidate_status_enum'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_designation_id'], ['designations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('outcome', sa.Enum('pending', 'pass', 'fail', name='interview_outcome_enum'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('basic', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pf_deduction', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('esi_deduction', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'month', 'year', name='uq_payslip_employee_month_year')
    )
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('basic', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pf_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('esi_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_structures')
    op.drop_table('payslips')
    op.drop_table('interviews')
    op.drop_table('asset_assignments')
    op.drop_table('candidates')
    op.drop_table('assets')
    # ### end Alembic commands ###
